import './globals.scss'
import { Inter, Rubik } from 'next/font/google'

const inter = Inter({ subsets: ['cyrillic'] })
const rubik = Rubik({ subsets: ['cyrillic'] })

export const metadata = {
  title: 'Sport Nutrition Premuim',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={rubik.className}>{children}</body>
    </html>
  )
}


